Repository tf-wallet-dscanner/tf-wallet-plasmo, pull requests merged in 2022-06, with the labels that each got.

#17 feat: typography 컴포넌트 추가
  src/components/atoms/typography/typography.scss
  src/components/atoms/typography/typography.tsx
  tailwind.config.js
Labels: feature, size/M

#18 feat: Box 컴포넌트 추가
  .prettierrc.cjs
  src/components/atoms/box/box.scss
  src/components/atoms/box/box.tsx
  src/components/atoms/box/index.ts
Labels: feature, size/M

#20 feat: Alert 컴포넌트 추가
  src/components/atoms/alert-icon/alert-icon.tsx
  src/components/atoms/alert/alert.scss
  src/components/atoms/alert/alert.tsx
  src/components/atoms/alert/index.ts
  src/pages/home.tsx
  src/pages/hong.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: feature, size/L

#23 icon button 추가
  package.json
  pnpm-lock.yaml
  src/components/atoms/button/button.scss
  src/components/atoms/button/button.tsx
  src/pages/home.tsx
Labels: feature, size/M

#24 chore: storybook 환경 세팅
  .storybook/main.js
  .storybook/preview.js
  package.json
  pnpm-lock.yaml
  src/components/atoms/typography/typography.stories.tsx
Labels: chore, size/XXL

#28 feat: Input Atomic 컴포넌트 추가
  .vscode/settings.json
  src/components/atoms/text-field/index.ts
  src/components/atoms/text-field/text-field.scss
  src/components/atoms/text-field/text-field.tsx
  src/constants/regex.ts
  src/pages/hong.tsx
Labels: feature, size/L
